/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationLogin } from "../funcs/authenticationLogin.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * OAuth authentication
   *
   * @remarks
   * Initiate OAuth authentication flow
   */
  async login(
    options?: RequestOptions,
  ): Promise<operations.InitiateOAuthLoginResponse> {
    return unwrapAsync(authenticationLogin(
      this,
      options,
    ));
  }
}
