/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationGetOAuthHealth } from "../funcs/authenticationGetOAuthHealth.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Get OAuth authentication health
   *
   * @remarks
   * Get health status of all OAuth credentials. Background service refreshes tokens 35 minutes before expiry. API calls mark tokens expired 5 minutes before expiry. Health statuses: 'healthy' (tokens valid, >5min remaining), 'degraded' (some tokens within 5min of expiry but refreshable), 'unhealthy' (tokens expired without refresh capability)
   */
  async getOAuthHealth(
    options?: RequestOptions,
  ): Promise<operations.GetOAuthHealthResponse> {
    return unwrapAsync(authenticationGetOAuthHealth(
      this,
      options,
    ));
  }
}
