/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationsRespondToNotification } from "../funcs/notificationsRespondToNotification.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Notifications extends ClientSDK {
  /**
   * Respond to notification
   *
   * @remarks
   * Send user's response to a notification request
   */
  async respondToNotification(
    request: operations.RespondToNotificationRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(notificationsRespondToNotification(
      this,
      request,
      options,
    ));
  }
}
