/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Authentication } from "./authentication.js";
import { Files } from "./files.js";
import { Messages } from "./messages.js";
import { Permissions } from "./permissions.js";
import { Preferences } from "./preferences.js";
import { Sessions } from "./sessions.js";
import { System } from "./system.js";
import { Tools } from "./tools.js";

export class Mix extends ClientSDK {
  private _authentication?: Authentication;
  get authentication(): Authentication {
    return (this._authentication ??= new Authentication(this._options));
  }

  private _system?: System;
  get system(): System {
    return (this._system ??= new System(this._options));
  }

  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _permissions?: Permissions;
  get permissions(): Permissions {
    return (this._permissions ??= new Permissions(this._options));
  }

  private _preferences?: Preferences;
  get preferences(): Preferences {
    return (this._preferences ??= new Preferences(this._options));
  }

  private _sessions?: Sessions;
  get sessions(): Sessions {
    return (this._sessions ??= new Sessions(this._options));
  }

  private _files?: Files;
  get files(): Files {
    return (this._files ??= new Files(this._options));
  }

  private _tools?: Tools;
  get tools(): Tools {
    return (this._tools ??= new Tools(this._options));
  }
}
