/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsCreate } from "../funcs/sessionsCreate.js";
import { sessionsDelete } from "../funcs/sessionsDelete.js";
import { sessionsExportSession } from "../funcs/sessionsExportSession.js";
import { sessionsGet } from "../funcs/sessionsGet.js";
import { sessionsList } from "../funcs/sessionsList.js";
import { sessionsRewindSession } from "../funcs/sessionsRewindSession.js";
import { sessionsUpdateSessionCallbacks } from "../funcs/sessionsUpdateSessionCallbacks.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sessions extends ClientSDK {
  /**
   * List all sessions
   *
   * @remarks
   * Retrieve a list of all available sessions with their metadata
   */
  async list(
    request?: operations.ListSessionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.SessionData>> {
    return unwrapAsync(sessionsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new session
   *
   * @remarks
   * Create a new session with required title and optional custom system prompt. Session automatically gets isolated storage directory. Supports session-level callbacks for automated actions after tool execution.
   */
  async create(
    request: operations.CreateSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionData> {
    return unwrapAsync(sessionsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a session
   *
   * @remarks
   * Permanently delete a session and all its data
   */
  async delete(
    request: operations.DeleteSessionRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sessionsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific session
   *
   * @remarks
   * Retrieve detailed information about a specific session
   */
  async get(
    request: operations.GetSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionData> {
    return unwrapAsync(sessionsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update session callbacks
   *
   * @remarks
   * Update the callback configurations for a session. Callbacks execute automatically after tool completion. Pass an empty array to clear all callbacks.
   */
  async updateSessionCallbacks(
    request: operations.UpdateSessionCallbacksRequest,
    options?: RequestOptions,
  ): Promise<models.SessionData> {
    return unwrapAsync(sessionsUpdateSessionCallbacks(
      this,
      request,
      options,
    ));
  }

  /**
   * Export session transcript
   *
   * @remarks
   * Export complete session transcript with all messages, tool calls, reasoning, and metadata as JSON
   */
  async exportSession(
    request: operations.ExportSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.ExportSessionResponse> {
    return unwrapAsync(sessionsExportSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Rewind a session
   *
   * @remarks
   * Delete messages after a specified message in the current session, optionally cleaning up media files created after that point
   */
  async rewindSession(
    request: operations.RewindSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionData> {
    return unwrapAsync(sessionsRewindSession(
      this,
      request,
      options,
    ));
  }
}
