/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsCreate } from "../funcs/sessionsCreate.js";
import { sessionsDelete } from "../funcs/sessionsDelete.js";
import { sessionsFork } from "../funcs/sessionsFork.js";
import { sessionsGet } from "../funcs/sessionsGet.js";
import { sessionsList } from "../funcs/sessionsList.js";
import { sessionsRewindSession } from "../funcs/sessionsRewindSession.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sessions extends ClientSDK {
  /**
   * List all sessions
   *
   * @remarks
   * Retrieve a list of all available sessions with their metadata
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<models.SessionData>> {
    return unwrapAsync(sessionsList(
      this,
      options,
    ));
  }

  /**
   * Create a new session
   *
   * @remarks
   * Create a new session with required title and optional custom system prompt. Session automatically gets isolated storage directory.
   */
  async create(
    request: operations.CreateSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionData> {
    return unwrapAsync(sessionsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a session
   *
   * @remarks
   * Permanently delete a session and all its data
   */
  async delete(
    request: operations.DeleteSessionRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sessionsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific session
   *
   * @remarks
   * Retrieve detailed information about a specific session
   */
  async get(
    request: operations.GetSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionData> {
    return unwrapAsync(sessionsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Fork a session
   *
   * @remarks
   * Create a new session based on an existing session, copying messages up to a specified index
   */
  async fork(
    request: operations.ForkSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionData> {
    return unwrapAsync(sessionsFork(
      this,
      request,
      options,
    ));
  }

  /**
   * Rewind a session
   *
   * @remarks
   * Delete messages after a specified message in the current session, optionally cleaning up media files created after that point
   */
  async rewindSession(
    request: operations.RewindSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionData> {
    return unwrapAsync(sessionsRewindSession(
      this,
      request,
      options,
    ));
  }
}
