/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsGetToolCredentialsStatus } from "../funcs/toolsGetToolCredentialsStatus.js";
import { toolsGetToolsStatus } from "../funcs/toolsGetToolsStatus.js";
import { toolsListLLMTools } from "../funcs/toolsListLLMTools.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tools extends ClientSDK {
  /**
   * List LLM tools
   *
   * @remarks
   * Returns the list of all LLM tools that Claude can invoke (Bash, Edit, Read, Write, Grep, Glob, WebFetch, WebSearch, ReadMedia, TodoWrite, ExitPlanMode, Task). This is useful for creating tool callbacks or understanding available agent capabilities.
   */
  async listLLMTools(
    options?: RequestOptions,
  ): Promise<operations.ListLLMToolsResponse> {
    return unwrapAsync(toolsListLLMTools(
      this,
      options,
    ));
  }

  /**
   * Get tool credentials status
   *
   * @remarks
   * Returns authentication/credential status for external tool integrations (Brave Search, Gemini Vision, etc.). This endpoint checks if API keys are configured for tools that require external service credentials.
   */
  async getToolCredentialsStatus(
    options?: RequestOptions,
  ): Promise<operations.GetToolCredentialsStatusResponse> {
    return unwrapAsync(toolsGetToolCredentialsStatus(
      this,
      options,
    ));
  }

  /**
   * Get tools status
   *
   * @remarks
   * Get status and authentication information for all available tools and categories
   */
  async getToolsStatus(
    options?: RequestOptions,
  ): Promise<operations.GetToolsStatusResponse> {
    return unwrapAsync(toolsGetToolsStatus(
      this,
      options,
    ));
  }
}
