/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsGetToolsStatus } from "../funcs/toolsGetToolsStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tools extends ClientSDK {
  /**
   * Get tools status
   *
   * @remarks
   * Get status and authentication information for all available tools and categories
   */
  async getToolsStatus(
    options?: RequestOptions,
  ): Promise<operations.GetToolsStatusResponse> {
    return unwrapAsync(toolsGetToolsStatus(
      this,
      options,
    ));
  }
}
