/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the mix-typescript-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx authSetApiKey.example.ts
 */

import { Mix } from "mix-typescript-sdk";

const mix = new Mix();

async function main() {
  const result = await mix.auth.setApiKey({
    apiKey: "<value>",
  });

  console.log(result);
}

main().catch(console.error);
