workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Mix REST API:
        inputs:
            - location: https://raw.githubusercontent.com/recreate-run/mix/main/mix_sdk/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: .speakeasy/speakeasy-modifications-overlay-1.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/recreate/mix/mix-rest-api
targets:
    mix-ts-target:
        target: typescript
        source: Mix REST API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/recreate/mix/mix-rest-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
