/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CancelSessionProcessingRequest = {
  /**
   * Session ID
   */
  id: string;
};

/**
 * Cancellation status
 */
export type CancelSessionProcessingResponse = {
  /**
   * Whether cancellation was successful
   */
  cancelled?: boolean | undefined;
};

/** @internal */
export type CancelSessionProcessingRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelSessionProcessingRequest$outboundSchema: z.ZodType<
  CancelSessionProcessingRequest$Outbound,
  z.ZodTypeDef,
  CancelSessionProcessingRequest
> = z.object({
  id: z.string(),
});

export function cancelSessionProcessingRequestToJSON(
  cancelSessionProcessingRequest: CancelSessionProcessingRequest,
): string {
  return JSON.stringify(
    CancelSessionProcessingRequest$outboundSchema.parse(
      cancelSessionProcessingRequest,
    ),
  );
}

/** @internal */
export const CancelSessionProcessingResponse$inboundSchema: z.ZodType<
  CancelSessionProcessingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  cancelled: z.boolean().optional(),
});

export function cancelSessionProcessingResponseFromJSON(
  jsonString: string,
): SafeParseResult<CancelSessionProcessingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CancelSessionProcessingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CancelSessionProcessingResponse' from JSON`,
  );
}
