/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Custom prompt handling mode:
 *
 * @remarks
 * - 'default': Use base system prompt only (customSystemPrompt ignored)
 * - 'append': Append customSystemPrompt to base system prompt (50KB limit)
 * - 'replace': Replace base system prompt with customSystemPrompt (100KB limit)
 */
export const PromptMode = {
  Default: "default",
  Append: "append",
  Replace: "replace",
} as const;
/**
 * Custom prompt handling mode:
 *
 * @remarks
 * - 'default': Use base system prompt only (customSystemPrompt ignored)
 * - 'append': Append customSystemPrompt to base system prompt (50KB limit)
 * - 'replace': Replace base system prompt with customSystemPrompt (100KB limit)
 */
export type PromptMode = ClosedEnum<typeof PromptMode>;

/**
 * Session type. API can only create 'main' sessions. Subagent sessions are created automatically by the task delegation system.
 */
export const SessionType = {
  Main: "main",
} as const;
/**
 * Session type. API can only create 'main' sessions. Subagent sessions are created automatically by the task delegation system.
 */
export type SessionType = ClosedEnum<typeof SessionType>;

export type CreateSessionRequest = {
  /**
   * Session-level callbacks that execute after tool completion. Environment variables available: CALLBACK_TOOL_RESULT, CALLBACK_TOOL_NAME, CALLBACK_TOOL_ID, CALLBACK_SESSION_ID
   */
  callbacks?: Array<models.Callback> | undefined;
  /**
   * Custom system prompt content. Size limits apply based on promptMode: 100KB (102,400 bytes) for replace mode, 50KB (51,200 bytes) for append mode. Ignored in default mode. Supports environment variable substitution with $<variable> syntax.
   */
  customSystemPrompt?: string | undefined;
  /**
   * Custom prompt handling mode:
   *
   * @remarks
   * - 'default': Use base system prompt only (customSystemPrompt ignored)
   * - 'append': Append customSystemPrompt to base system prompt (50KB limit)
   * - 'replace': Replace base system prompt with customSystemPrompt (100KB limit)
   */
  promptMode?: PromptMode | undefined;
  /**
   * Session type. API can only create 'main' sessions. Subagent sessions are created automatically by the task delegation system.
   */
  sessionType?: SessionType | undefined;
  /**
   * Subagent type - must not be set for API-created sessions. This field is reserved for programmatic subagent creation.
   */
  subagentType?: string | undefined;
  /**
   * Title for the session
   */
  title: string;
};

/** @internal */
export const PromptMode$outboundSchema: z.ZodNativeEnum<typeof PromptMode> = z
  .nativeEnum(PromptMode);

/** @internal */
export const SessionType$outboundSchema: z.ZodNativeEnum<typeof SessionType> = z
  .nativeEnum(SessionType);

/** @internal */
export type CreateSessionRequest$Outbound = {
  callbacks?: Array<models.Callback$Outbound> | undefined;
  customSystemPrompt?: string | undefined;
  promptMode: string;
  sessionType: string;
  subagentType?: string | undefined;
  title: string;
};

/** @internal */
export const CreateSessionRequest$outboundSchema: z.ZodType<
  CreateSessionRequest$Outbound,
  z.ZodTypeDef,
  CreateSessionRequest
> = z.object({
  callbacks: z.array(models.Callback$outboundSchema).optional(),
  customSystemPrompt: z.string().optional(),
  promptMode: PromptMode$outboundSchema.default("default"),
  sessionType: SessionType$outboundSchema.default("main"),
  subagentType: z.string().optional(),
  title: z.string(),
});

export function createSessionRequestToJSON(
  createSessionRequest: CreateSessionRequest,
): string {
  return JSON.stringify(
    CreateSessionRequest$outboundSchema.parse(createSessionRequest),
  );
}
