/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteSessionRequest = {
  /**
   * Session ID
   */
  id: string;
};

/** @internal */
export const DeleteSessionRequest$inboundSchema: z.ZodType<
  DeleteSessionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteSessionRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteSessionRequest$outboundSchema: z.ZodType<
  DeleteSessionRequest$Outbound,
  z.ZodTypeDef,
  DeleteSessionRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteSessionRequest$ {
  /** @deprecated use `DeleteSessionRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteSessionRequest$inboundSchema;
  /** @deprecated use `DeleteSessionRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteSessionRequest$outboundSchema;
  /** @deprecated use `DeleteSessionRequest$Outbound` instead. */
  export type Outbound = DeleteSessionRequest$Outbound;
}

export function deleteSessionRequestToJSON(
  deleteSessionRequest: DeleteSessionRequest,
): string {
  return JSON.stringify(
    DeleteSessionRequest$outboundSchema.parse(deleteSessionRequest),
  );
}

export function deleteSessionRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSessionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSessionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSessionRequest' from JSON`,
  );
}
