/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteCredentialsRequest = {
  /**
   * Provider name (anthropic, openai, openrouter, gemini, brave)
   */
  provider: string;
};

/**
 * Credentials deletion status
 */
export type DeleteCredentialsResponse = {
  /**
   * Status message
   */
  message?: string | undefined;
  /**
   * Provider name
   */
  provider?: string | undefined;
  /**
   * Operation status
   */
  status?: string | undefined;
};

/** @internal */
export type DeleteCredentialsRequest$Outbound = {
  provider: string;
};

/** @internal */
export const DeleteCredentialsRequest$outboundSchema: z.ZodType<
  DeleteCredentialsRequest$Outbound,
  z.ZodTypeDef,
  DeleteCredentialsRequest
> = z.object({
  provider: z.string(),
});

export function deleteCredentialsRequestToJSON(
  deleteCredentialsRequest: DeleteCredentialsRequest,
): string {
  return JSON.stringify(
    DeleteCredentialsRequest$outboundSchema.parse(deleteCredentialsRequest),
  );
}

/** @internal */
export const DeleteCredentialsResponse$inboundSchema: z.ZodType<
  DeleteCredentialsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  provider: z.string().optional(),
  status: z.string().optional(),
});

export function deleteCredentialsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteCredentialsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteCredentialsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteCredentialsResponse' from JSON`,
  );
}
