/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteSessionFileRequest = {
  /**
   * Session ID
   */
  id: string;
  /**
   * Filename to delete
   */
  filename: string;
};

/** @internal */
export type DeleteSessionFileRequest$Outbound = {
  id: string;
  filename: string;
};

/** @internal */
export const DeleteSessionFileRequest$outboundSchema: z.ZodType<
  DeleteSessionFileRequest$Outbound,
  z.ZodTypeDef,
  DeleteSessionFileRequest
> = z.object({
  id: z.string(),
  filename: z.string(),
});

export function deleteSessionFileRequestToJSON(
  deleteSessionFileRequest: DeleteSessionFileRequest,
): string {
  return JSON.stringify(
    DeleteSessionFileRequest$outboundSchema.parse(deleteSessionFileRequest),
  );
}
