/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DenyPermissionRequest = {
  /**
   * Permission ID
   */
  id: string;
};

/**
 * Permission deny status
 */
export type DenyPermissionResponse = {
  /**
   * Whether permission was denied
   */
  denied?: boolean | undefined;
};

/** @internal */
export type DenyPermissionRequest$Outbound = {
  id: string;
};

/** @internal */
export const DenyPermissionRequest$outboundSchema: z.ZodType<
  DenyPermissionRequest$Outbound,
  z.ZodTypeDef,
  DenyPermissionRequest
> = z.object({
  id: z.string(),
});

export function denyPermissionRequestToJSON(
  denyPermissionRequest: DenyPermissionRequest,
): string {
  return JSON.stringify(
    DenyPermissionRequest$outboundSchema.parse(denyPermissionRequest),
  );
}

/** @internal */
export const DenyPermissionResponse$inboundSchema: z.ZodType<
  DenyPermissionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  denied: z.boolean().optional(),
});

export function denyPermissionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DenyPermissionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DenyPermissionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DenyPermissionResponse' from JSON`,
  );
}
