/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ExportSessionRequest = {
  /**
   * Session ID to export
   */
  id: string;
};

export type ExportSessionResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ExportSession;
};

/** @internal */
export type ExportSessionRequest$Outbound = {
  id: string;
};

/** @internal */
export const ExportSessionRequest$outboundSchema: z.ZodType<
  ExportSessionRequest$Outbound,
  z.ZodTypeDef,
  ExportSessionRequest
> = z.object({
  id: z.string(),
});

export function exportSessionRequestToJSON(
  exportSessionRequest: ExportSessionRequest,
): string {
  return JSON.stringify(
    ExportSessionRequest$outboundSchema.parse(exportSessionRequest),
  );
}

/** @internal */
export const ExportSessionResponse$inboundSchema: z.ZodType<
  ExportSessionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ExportSession$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function exportSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExportSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExportSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExportSessionResponse' from JSON`,
  );
}
