/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ForkSessionRequestBody = {
  /**
   * Index of the last message to include in the fork (0-based)
   */
  messageIndex: number;
  /**
   * Optional title for the forked session (defaults to 'Forked Session')
   */
  title?: string | undefined;
};

export type ForkSessionRequest = {
  /**
   * Source session ID to fork from
   */
  id: string;
  requestBody: ForkSessionRequestBody;
};

/** @internal */
export type ForkSessionRequestBody$Outbound = {
  messageIndex: number;
  title?: string | undefined;
};

/** @internal */
export const ForkSessionRequestBody$outboundSchema: z.ZodType<
  ForkSessionRequestBody$Outbound,
  z.ZodTypeDef,
  ForkSessionRequestBody
> = z.object({
  messageIndex: z.number().int(),
  title: z.string().optional(),
});

export function forkSessionRequestBodyToJSON(
  forkSessionRequestBody: ForkSessionRequestBody,
): string {
  return JSON.stringify(
    ForkSessionRequestBody$outboundSchema.parse(forkSessionRequestBody),
  );
}

/** @internal */
export type ForkSessionRequest$Outbound = {
  id: string;
  RequestBody: ForkSessionRequestBody$Outbound;
};

/** @internal */
export const ForkSessionRequest$outboundSchema: z.ZodType<
  ForkSessionRequest$Outbound,
  z.ZodTypeDef,
  ForkSessionRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => ForkSessionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function forkSessionRequestToJSON(
  forkSessionRequest: ForkSessionRequest,
): string {
  return JSON.stringify(
    ForkSessionRequest$outboundSchema.parse(forkSessionRequest),
  );
}
