/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Authentication method (oauth, api_key, none)
 */
export const GetAuthStatusAuthMethod = {
  Oauth: "oauth",
  ApiKey: "api_key",
  None: "none",
} as const;
/**
 * Authentication method (oauth, api_key, none)
 */
export type GetAuthStatusAuthMethod = ClosedEnum<
  typeof GetAuthStatusAuthMethod
>;

export type GetAuthStatusProviders = {
  /**
   * Authentication method (oauth, api_key, none)
   */
  authMethod?: GetAuthStatusAuthMethod | undefined;
  /**
   * Whether provider is authenticated
   */
  authenticated?: boolean | undefined;
  /**
   * User-friendly provider name
   */
  displayName?: string | undefined;
};

/**
 * Authentication status for all providers
 */
export type GetAuthStatusResponse = {
  /**
   * Map of provider authentication status
   */
  providers?: { [k: string]: GetAuthStatusProviders } | undefined;
};

/** @internal */
export const GetAuthStatusAuthMethod$inboundSchema: z.ZodNativeEnum<
  typeof GetAuthStatusAuthMethod
> = z.nativeEnum(GetAuthStatusAuthMethod);

/** @internal */
export const GetAuthStatusProviders$inboundSchema: z.ZodType<
  GetAuthStatusProviders,
  z.ZodTypeDef,
  unknown
> = z.object({
  auth_method: GetAuthStatusAuthMethod$inboundSchema.optional(),
  authenticated: z.boolean().optional(),
  display_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "auth_method": "authMethod",
    "display_name": "displayName",
  });
});

export function getAuthStatusProvidersFromJSON(
  jsonString: string,
): SafeParseResult<GetAuthStatusProviders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAuthStatusProviders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAuthStatusProviders' from JSON`,
  );
}

/** @internal */
export const GetAuthStatusResponse$inboundSchema: z.ZodType<
  GetAuthStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  providers: z.record(z.lazy(() => GetAuthStatusProviders$inboundSchema))
    .optional(),
});

export function getAuthStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAuthStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAuthStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAuthStatusResponse' from JSON`,
  );
}
