/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAvailableProvidersResponse = {
  /**
   * Provider display name
   */
  displayName?: string | undefined;
  /**
   * Available models for this provider
   */
  models?: Array<string> | undefined;
};

/** @internal */
export const GetAvailableProvidersResponse$inboundSchema: z.ZodType<
  GetAvailableProvidersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string().optional(),
  models: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
  });
});

export function getAvailableProvidersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAvailableProvidersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAvailableProvidersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAvailableProvidersResponse' from JSON`,
  );
}
