/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCommandRequest = {
  /**
   * Command name
   */
  name: string;
};

/**
 * Command details
 */
export type GetCommandResponse = {
  /**
   * Command description
   */
  description?: string | undefined;
  /**
   * Command name
   */
  name?: string | undefined;
  /**
   * Command usage instructions
   */
  usage?: string | undefined;
};

/** @internal */
export type GetCommandRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetCommandRequest$outboundSchema: z.ZodType<
  GetCommandRequest$Outbound,
  z.ZodTypeDef,
  GetCommandRequest
> = z.object({
  name: z.string(),
});

export function getCommandRequestToJSON(
  getCommandRequest: GetCommandRequest,
): string {
  return JSON.stringify(
    GetCommandRequest$outboundSchema.parse(getCommandRequest),
  );
}

/** @internal */
export const GetCommandResponse$inboundSchema: z.ZodType<
  GetCommandResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  name: z.string().optional(),
  usage: z.string().optional(),
});

export function getCommandResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCommandResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCommandResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCommandResponse' from JSON`,
  );
}
