/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetMessageHistoryRequest = {
  /**
   * Maximum number of messages to return
   */
  limit?: number | undefined;
  /**
   * Number of messages to skip
   */
  offset?: number | undefined;
};

/** @internal */
export type GetMessageHistoryRequest$Outbound = {
  limit: number;
  offset: number;
};

/** @internal */
export const GetMessageHistoryRequest$outboundSchema: z.ZodType<
  GetMessageHistoryRequest$Outbound,
  z.ZodTypeDef,
  GetMessageHistoryRequest
> = z.object({
  limit: z.number().int().default(50),
  offset: z.number().int().default(0),
});

export function getMessageHistoryRequestToJSON(
  getMessageHistoryRequest: GetMessageHistoryRequest,
): string {
  return JSON.stringify(
    GetMessageHistoryRequest$outboundSchema.parse(getMessageHistoryRequest),
  );
}
