/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Token status
 */
export const ProvidersStatus = {
  Active: "active",
  Expired: "expired",
  ExpiredNoRefresh: "expired_no_refresh",
  Error: "error",
  NotFound: "not_found",
} as const;
/**
 * Token status
 */
export type ProvidersStatus = ClosedEnum<typeof ProvidersStatus>;

export type GetOAuthHealthProviders = {
  /**
   * Error message if status is 'error'
   */
  error?: string | undefined;
  /**
   * Token expiration time
   */
  expiresAt?: Date | undefined;
  /**
   * Human-readable time until expiration
   */
  expiresIn?: string | undefined;
  /**
   * Last time token was refreshed
   */
  lastRefresh?: Date | undefined;
  /**
   * Provider name
   */
  provider: string;
  /**
   * Token status
   */
  status: ProvidersStatus;
};

/**
 * Overall health status
 */
export const Status = {
  Healthy: "healthy",
  Degraded: "degraded",
  Unhealthy: "unhealthy",
} as const;
/**
 * Overall health status
 */
export type Status = ClosedEnum<typeof Status>;

/**
 * OAuth health status
 */
export type GetOAuthHealthResponse = {
  /**
   * Map of provider OAuth health status
   */
  providers: { [k: string]: GetOAuthHealthProviders };
  /**
   * Overall health status
   */
  status: Status;
  /**
   * Health check timestamp
   */
  timestamp: Date;
};

/** @internal */
export const ProvidersStatus$inboundSchema: z.ZodNativeEnum<
  typeof ProvidersStatus
> = z.nativeEnum(ProvidersStatus);

/** @internal */
export const GetOAuthHealthProviders$inboundSchema: z.ZodType<
  GetOAuthHealthProviders,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  expires_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  expires_in: z.string().optional(),
  last_refresh: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  provider: z.string(),
  status: ProvidersStatus$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "expires_at": "expiresAt",
    "expires_in": "expiresIn",
    "last_refresh": "lastRefresh",
  });
});

export function getOAuthHealthProvidersFromJSON(
  jsonString: string,
): SafeParseResult<GetOAuthHealthProviders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOAuthHealthProviders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOAuthHealthProviders' from JSON`,
  );
}

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const GetOAuthHealthResponse$inboundSchema: z.ZodType<
  GetOAuthHealthResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  providers: z.record(z.lazy(() => GetOAuthHealthProviders$inboundSchema)),
  status: Status$inboundSchema,
  timestamp: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function getOAuthHealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOAuthHealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOAuthHealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOAuthHealthResponse' from JSON`,
  );
}
