/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AvailableProviders = {
  /**
   * User-friendly provider name
   */
  displayName?: string | undefined;
  /**
   * Available models from this provider
   */
  models?: Array<string> | undefined;
};

/**
 * User preferences (null if no preferences exist)
 */
export type Preferences = {
  /**
   * Unix timestamp when preferences were created
   */
  createdAt?: number | undefined;
  /**
   * Maximum tokens for main agent responses
   */
  mainAgentMaxTokens?: number | undefined;
  /**
   * Main agent model ID
   */
  mainAgentModel?: string | undefined;
  /**
   * Reasoning effort setting for main agent
   */
  mainAgentReasoningEffort?: string | undefined;
  /**
   * Preferred AI provider (anthropic, openai, openrouter)
   */
  preferredProvider?: string | undefined;
  /**
   * Maximum tokens for sub agent responses
   */
  subAgentMaxTokens?: number | undefined;
  /**
   * Sub agent model ID
   */
  subAgentModel?: string | undefined;
  /**
   * Reasoning effort setting for sub agent
   */
  subAgentReasoningEffort?: string | undefined;
  /**
   * Unix timestamp of last update
   */
  updatedAt?: number | undefined;
};

/**
 * User preferences and available providers
 */
export type GetPreferencesResponse = {
  /**
   * Map of available AI providers and their models
   */
  availableProviders: { [k: string]: AvailableProviders };
  /**
   * User preferences (null if no preferences exist)
   */
  preferences?: Preferences | null | undefined;
};

/** @internal */
export const AvailableProviders$inboundSchema: z.ZodType<
  AvailableProviders,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string().optional(),
  models: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
  });
});

export function availableProvidersFromJSON(
  jsonString: string,
): SafeParseResult<AvailableProviders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AvailableProviders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AvailableProviders' from JSON`,
  );
}

/** @internal */
export const Preferences$inboundSchema: z.ZodType<
  Preferences,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.number().int().optional(),
  main_agent_max_tokens: z.number().int().optional(),
  main_agent_model: z.string().optional(),
  main_agent_reasoning_effort: z.string().optional(),
  preferred_provider: z.string().optional(),
  sub_agent_max_tokens: z.number().int().optional(),
  sub_agent_model: z.string().optional(),
  sub_agent_reasoning_effort: z.string().optional(),
  updated_at: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "main_agent_max_tokens": "mainAgentMaxTokens",
    "main_agent_model": "mainAgentModel",
    "main_agent_reasoning_effort": "mainAgentReasoningEffort",
    "preferred_provider": "preferredProvider",
    "sub_agent_max_tokens": "subAgentMaxTokens",
    "sub_agent_model": "subAgentModel",
    "sub_agent_reasoning_effort": "subAgentReasoningEffort",
    "updated_at": "updatedAt",
  });
});

export function preferencesFromJSON(
  jsonString: string,
): SafeParseResult<Preferences, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Preferences$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Preferences' from JSON`,
  );
}

/** @internal */
export const GetPreferencesResponse$inboundSchema: z.ZodType<
  GetPreferencesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  available_providers: z.record(z.lazy(() => AvailableProviders$inboundSchema)),
  preferences: z.nullable(z.lazy(() => Preferences$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "available_providers": "availableProviders",
  });
});

export function getPreferencesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPreferencesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPreferencesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPreferencesResponse' from JSON`,
  );
}
