/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AvailableProviders = {
  /**
   * User-friendly provider name
   */
  displayName?: string | undefined;
  /**
   * Available models from this provider
   */
  models?: Array<string> | undefined;
};

/**
 * User preferences (null if no preferences exist)
 */
export type Preferences = {
  /**
   * Unix timestamp when preferences were created
   */
  createdAt?: number | undefined;
  /**
   * Maximum tokens for main agent responses
   */
  mainAgentMaxTokens?: number | undefined;
  /**
   * Main agent model ID
   */
  mainAgentModel?: string | undefined;
  /**
   * Reasoning effort setting for main agent
   */
  mainAgentReasoningEffort?: string | undefined;
  /**
   * Preferred AI provider (anthropic, openai, openrouter)
   */
  preferredProvider?: string | undefined;
  /**
   * Maximum tokens for sub agent responses
   */
  subAgentMaxTokens?: number | undefined;
  /**
   * Sub agent model ID
   */
  subAgentModel?: string | undefined;
  /**
   * Reasoning effort setting for sub agent
   */
  subAgentReasoningEffort?: string | undefined;
  /**
   * Unix timestamp of last update
   */
  updatedAt?: number | undefined;
};

/**
 * User preferences and available providers
 */
export type GetPreferencesResponse = {
  /**
   * Map of available AI providers and their models
   */
  availableProviders: { [k: string]: AvailableProviders };
  /**
   * User preferences (null if no preferences exist)
   */
  preferences?: Preferences | null | undefined;
};

/** @internal */
export const AvailableProviders$inboundSchema: z.ZodType<
  AvailableProviders,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string().optional(),
  models: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
  });
});

/** @internal */
export type AvailableProviders$Outbound = {
  display_name?: string | undefined;
  models?: Array<string> | undefined;
};

/** @internal */
export const AvailableProviders$outboundSchema: z.ZodType<
  AvailableProviders$Outbound,
  z.ZodTypeDef,
  AvailableProviders
> = z.object({
  displayName: z.string().optional(),
  models: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AvailableProviders$ {
  /** @deprecated use `AvailableProviders$inboundSchema` instead. */
  export const inboundSchema = AvailableProviders$inboundSchema;
  /** @deprecated use `AvailableProviders$outboundSchema` instead. */
  export const outboundSchema = AvailableProviders$outboundSchema;
  /** @deprecated use `AvailableProviders$Outbound` instead. */
  export type Outbound = AvailableProviders$Outbound;
}

export function availableProvidersToJSON(
  availableProviders: AvailableProviders,
): string {
  return JSON.stringify(
    AvailableProviders$outboundSchema.parse(availableProviders),
  );
}

export function availableProvidersFromJSON(
  jsonString: string,
): SafeParseResult<AvailableProviders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AvailableProviders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AvailableProviders' from JSON`,
  );
}

/** @internal */
export const Preferences$inboundSchema: z.ZodType<
  Preferences,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.number().int().optional(),
  main_agent_max_tokens: z.number().int().optional(),
  main_agent_model: z.string().optional(),
  main_agent_reasoning_effort: z.string().optional(),
  preferred_provider: z.string().optional(),
  sub_agent_max_tokens: z.number().int().optional(),
  sub_agent_model: z.string().optional(),
  sub_agent_reasoning_effort: z.string().optional(),
  updated_at: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "main_agent_max_tokens": "mainAgentMaxTokens",
    "main_agent_model": "mainAgentModel",
    "main_agent_reasoning_effort": "mainAgentReasoningEffort",
    "preferred_provider": "preferredProvider",
    "sub_agent_max_tokens": "subAgentMaxTokens",
    "sub_agent_model": "subAgentModel",
    "sub_agent_reasoning_effort": "subAgentReasoningEffort",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type Preferences$Outbound = {
  created_at?: number | undefined;
  main_agent_max_tokens?: number | undefined;
  main_agent_model?: string | undefined;
  main_agent_reasoning_effort?: string | undefined;
  preferred_provider?: string | undefined;
  sub_agent_max_tokens?: number | undefined;
  sub_agent_model?: string | undefined;
  sub_agent_reasoning_effort?: string | undefined;
  updated_at?: number | undefined;
};

/** @internal */
export const Preferences$outboundSchema: z.ZodType<
  Preferences$Outbound,
  z.ZodTypeDef,
  Preferences
> = z.object({
  createdAt: z.number().int().optional(),
  mainAgentMaxTokens: z.number().int().optional(),
  mainAgentModel: z.string().optional(),
  mainAgentReasoningEffort: z.string().optional(),
  preferredProvider: z.string().optional(),
  subAgentMaxTokens: z.number().int().optional(),
  subAgentModel: z.string().optional(),
  subAgentReasoningEffort: z.string().optional(),
  updatedAt: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    mainAgentMaxTokens: "main_agent_max_tokens",
    mainAgentModel: "main_agent_model",
    mainAgentReasoningEffort: "main_agent_reasoning_effort",
    preferredProvider: "preferred_provider",
    subAgentMaxTokens: "sub_agent_max_tokens",
    subAgentModel: "sub_agent_model",
    subAgentReasoningEffort: "sub_agent_reasoning_effort",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Preferences$ {
  /** @deprecated use `Preferences$inboundSchema` instead. */
  export const inboundSchema = Preferences$inboundSchema;
  /** @deprecated use `Preferences$outboundSchema` instead. */
  export const outboundSchema = Preferences$outboundSchema;
  /** @deprecated use `Preferences$Outbound` instead. */
  export type Outbound = Preferences$Outbound;
}

export function preferencesToJSON(preferences: Preferences): string {
  return JSON.stringify(Preferences$outboundSchema.parse(preferences));
}

export function preferencesFromJSON(
  jsonString: string,
): SafeParseResult<Preferences, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Preferences$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Preferences' from JSON`,
  );
}

/** @internal */
export const GetPreferencesResponse$inboundSchema: z.ZodType<
  GetPreferencesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  available_providers: z.record(z.lazy(() => AvailableProviders$inboundSchema)),
  preferences: z.nullable(z.lazy(() => Preferences$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "available_providers": "availableProviders",
  });
});

/** @internal */
export type GetPreferencesResponse$Outbound = {
  available_providers: { [k: string]: AvailableProviders$Outbound };
  preferences?: Preferences$Outbound | null | undefined;
};

/** @internal */
export const GetPreferencesResponse$outboundSchema: z.ZodType<
  GetPreferencesResponse$Outbound,
  z.ZodTypeDef,
  GetPreferencesResponse
> = z.object({
  availableProviders: z.record(z.lazy(() => AvailableProviders$outboundSchema)),
  preferences: z.nullable(z.lazy(() => Preferences$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    availableProviders: "available_providers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPreferencesResponse$ {
  /** @deprecated use `GetPreferencesResponse$inboundSchema` instead. */
  export const inboundSchema = GetPreferencesResponse$inboundSchema;
  /** @deprecated use `GetPreferencesResponse$outboundSchema` instead. */
  export const outboundSchema = GetPreferencesResponse$outboundSchema;
  /** @deprecated use `GetPreferencesResponse$Outbound` instead. */
  export type Outbound = GetPreferencesResponse$Outbound;
}

export function getPreferencesResponseToJSON(
  getPreferencesResponse: GetPreferencesResponse,
): string {
  return JSON.stringify(
    GetPreferencesResponse$outboundSchema.parse(getPreferencesResponse),
  );
}

export function getPreferencesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPreferencesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPreferencesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPreferencesResponse' from JSON`,
  );
}
