/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetSessionRequest = {
  /**
   * Session ID
   */
  id: string;
};

/** @internal */
export type GetSessionRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSessionRequest$outboundSchema: z.ZodType<
  GetSessionRequest$Outbound,
  z.ZodTypeDef,
  GetSessionRequest
> = z.object({
  id: z.string(),
});

export function getSessionRequestToJSON(
  getSessionRequest: GetSessionRequest,
): string {
  return JSON.stringify(
    GetSessionRequest$outboundSchema.parse(getSessionRequest),
  );
}
