/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetSessionMessagesRequest = {
  /**
   * Session ID
   */
  id: string;
};

/** @internal */
export type GetSessionMessagesRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSessionMessagesRequest$outboundSchema: z.ZodType<
  GetSessionMessagesRequest$Outbound,
  z.ZodTypeDef,
  GetSessionMessagesRequest
> = z.object({
  id: z.string(),
});

export function getSessionMessagesRequestToJSON(
  getSessionMessagesRequest: GetSessionMessagesRequest,
): string {
  return JSON.stringify(
    GetSessionMessagesRequest$outboundSchema.parse(getSessionMessagesRequest),
  );
}
