/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetToolsStatusTool = {
  /**
   * Whether tool requires API key authentication
   */
  apiKeyRequired?: boolean | undefined;
  /**
   * Whether tool is authenticated and ready to use
   */
  authenticated?: boolean | undefined;
  /**
   * Tool description
   */
  description?: string | undefined;
  /**
   * User-friendly tool name
   */
  displayName?: string | undefined;
  /**
   * Tool provider name
   */
  provider?: string | undefined;
};

export type GetToolsStatusCategories = {
  /**
   * User-friendly category name
   */
  displayName?: string | undefined;
  /**
   * Available tools in this category
   */
  tools?: Array<GetToolsStatusTool> | undefined;
};

/**
 * Tools status and authentication information
 */
export type GetToolsStatusResponse = {
  /**
   * Map of tool categories and their tools
   */
  categories?: { [k: string]: GetToolsStatusCategories } | undefined;
};

/** @internal */
export const GetToolsStatusTool$inboundSchema: z.ZodType<
  GetToolsStatusTool,
  z.ZodTypeDef,
  unknown
> = z.object({
  api_key_required: z.boolean().optional(),
  authenticated: z.boolean().optional(),
  description: z.string().optional(),
  display_name: z.string().optional(),
  provider: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "api_key_required": "apiKeyRequired",
    "display_name": "displayName",
  });
});

export function getToolsStatusToolFromJSON(
  jsonString: string,
): SafeParseResult<GetToolsStatusTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetToolsStatusTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetToolsStatusTool' from JSON`,
  );
}

/** @internal */
export const GetToolsStatusCategories$inboundSchema: z.ZodType<
  GetToolsStatusCategories,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string().optional(),
  tools: z.array(z.lazy(() => GetToolsStatusTool$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
  });
});

export function getToolsStatusCategoriesFromJSON(
  jsonString: string,
): SafeParseResult<GetToolsStatusCategories, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetToolsStatusCategories$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetToolsStatusCategories' from JSON`,
  );
}

/** @internal */
export const GetToolsStatusResponse$inboundSchema: z.ZodType<
  GetToolsStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  categories: z.record(z.lazy(() => GetToolsStatusCategories$inboundSchema))
    .optional(),
});

export function getToolsStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetToolsStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetToolsStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetToolsStatusResponse' from JSON`,
  );
}
