/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type HandleOAuthCallbackRequest = {
  /**
   * Authorization code from OAuth provider
   */
  code: string;
  /**
   * Provider name (anthropic)
   */
  provider: string;
  /**
   * OAuth state for verification
   */
  state: string;
};

/**
 * OAuth completion status
 */
export type HandleOAuthCallbackResponse = {
  /**
   * Seconds until token expiration
   */
  expiresIn?: number | undefined;
  /**
   * Status message
   */
  message?: string | undefined;
  /**
   * Provider name
   */
  provider?: string | undefined;
  /**
   * Operation status
   */
  status?: string | undefined;
};

/** @internal */
export type HandleOAuthCallbackRequest$Outbound = {
  code: string;
  provider: string;
  state: string;
};

/** @internal */
export const HandleOAuthCallbackRequest$outboundSchema: z.ZodType<
  HandleOAuthCallbackRequest$Outbound,
  z.ZodTypeDef,
  HandleOAuthCallbackRequest
> = z.object({
  code: z.string(),
  provider: z.string(),
  state: z.string(),
});

export function handleOAuthCallbackRequestToJSON(
  handleOAuthCallbackRequest: HandleOAuthCallbackRequest,
): string {
  return JSON.stringify(
    HandleOAuthCallbackRequest$outboundSchema.parse(handleOAuthCallbackRequest),
  );
}

/** @internal */
export const HandleOAuthCallbackResponse$inboundSchema: z.ZodType<
  HandleOAuthCallbackResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  expires_in: z.number().int().optional(),
  message: z.string().optional(),
  provider: z.string().optional(),
  status: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "expires_in": "expiresIn",
  });
});

export function handleOAuthCallbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<HandleOAuthCallbackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HandleOAuthCallbackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HandleOAuthCallbackResponse' from JSON`,
  );
}
