/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Health information
 */
export type HealthCheckResponse = {
  /**
   * Health status
   */
  status?: string | undefined;
  /**
   * Current timestamp
   */
  timestamp?: string | undefined;
  /**
   * Application version
   */
  version?: string | undefined;
};

/** @internal */
export const HealthCheckResponse$inboundSchema: z.ZodType<
  HealthCheckResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string().optional(),
  timestamp: z.string().optional(),
  version: z.string().optional(),
});

export function healthCheckResponseFromJSON(
  jsonString: string,
): SafeParseResult<HealthCheckResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HealthCheckResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HealthCheckResponse' from JSON`,
  );
}
