/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListSessionFilesRequest = {
  /**
   * Session ID
   */
  id: string;
};

/** @internal */
export type ListSessionFilesRequest$Outbound = {
  id: string;
};

/** @internal */
export const ListSessionFilesRequest$outboundSchema: z.ZodType<
  ListSessionFilesRequest$Outbound,
  z.ZodTypeDef,
  ListSessionFilesRequest
> = z.object({
  id: z.string(),
});

export function listSessionFilesRequestToJSON(
  listSessionFilesRequest: ListSessionFilesRequest,
): string {
  return JSON.stringify(
    ListSessionFilesRequest$outboundSchema.parse(listSessionFilesRequest),
  );
}
