/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListSessionsRequest = {
  /**
   * Include subagent sessions in response (default: false, subagent sessions are hidden)
   */
  includeSubagents?: boolean | undefined;
};

/** @internal */
export type ListSessionsRequest$Outbound = {
  includeSubagents: boolean;
};

/** @internal */
export const ListSessionsRequest$outboundSchema: z.ZodType<
  ListSessionsRequest$Outbound,
  z.ZodTypeDef,
  ListSessionsRequest
> = z.object({
  includeSubagents: z.boolean().default(false),
});

export function listSessionsRequestToJSON(
  listSessionsRequest: ListSessionsRequest,
): string {
  return JSON.stringify(
    ListSessionsRequest$outboundSchema.parse(listSessionsRequest),
  );
}
