/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListMcpServersTool = {
  /**
   * Tool description
   */
  description: string;
  /**
   * Tool name
   */
  name: string;
};

export type ListMcpServersResponse = {
  /**
   * Whether the MCP server is currently connected
   */
  connected: boolean;
  /**
   * MCP server name
   */
  name: string;
  /**
   * Server connection status (e.g., 'connected', 'failed', 'disconnected')
   */
  status: string;
  /**
   * List of tools provided by this MCP server (null if server is not connected)
   */
  tools?: Array<ListMcpServersTool> | null | undefined;
};

/** @internal */
export const ListMcpServersTool$inboundSchema: z.ZodType<
  ListMcpServersTool,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string(),
  name: z.string(),
});

export function listMcpServersToolFromJSON(
  jsonString: string,
): SafeParseResult<ListMcpServersTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMcpServersTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMcpServersTool' from JSON`,
  );
}

/** @internal */
export const ListMcpServersResponse$inboundSchema: z.ZodType<
  ListMcpServersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  connected: z.boolean(),
  name: z.string(),
  status: z.string(),
  tools: z.nullable(z.array(z.lazy(() => ListMcpServersTool$inboundSchema)))
    .optional(),
});

export function listMcpServersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMcpServersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMcpServersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMcpServersResponse' from JSON`,
  );
}
