/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Tool parameter schema
 */
export type ParametersT = {};

export type ListLLMToolsTool = {
  /**
   * Tool description
   */
  description?: string | undefined;
  /**
   * Tool name
   */
  name?: string | undefined;
  /**
   * Tool parameter schema
   */
  parameters?: ParametersT | undefined;
  /**
   * Required parameters
   */
  required?: Array<string> | undefined;
};

/**
 * List of LLM tools
 */
export type ListLLMToolsResponse = {
  tools?: Array<ListLLMToolsTool> | undefined;
};

/** @internal */
export const ParametersT$inboundSchema: z.ZodType<
  ParametersT,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function parametersFromJSON(
  jsonString: string,
): SafeParseResult<ParametersT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ParametersT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ParametersT' from JSON`,
  );
}

/** @internal */
export const ListLLMToolsTool$inboundSchema: z.ZodType<
  ListLLMToolsTool,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  name: z.string().optional(),
  parameters: z.lazy(() => ParametersT$inboundSchema).optional(),
  required: z.array(z.string()).optional(),
});

export function listLLMToolsToolFromJSON(
  jsonString: string,
): SafeParseResult<ListLLMToolsTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLLMToolsTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLLMToolsTool' from JSON`,
  );
}

/** @internal */
export const ListLLMToolsResponse$inboundSchema: z.ZodType<
  ListLLMToolsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  tools: z.array(z.lazy(() => ListLLMToolsTool$inboundSchema)).optional(),
});

export function listLLMToolsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListLLMToolsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLLMToolsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLLMToolsResponse' from JSON`,
  );
}
