/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Reset preferences
 */
export type ResetPreferencesResponse = {
  /**
   * Creation timestamp
   */
  createdAt?: number | undefined;
  /**
   * Reset main agent max tokens
   */
  mainAgentMaxTokens?: number | undefined;
  /**
   * Reset main agent model
   */
  mainAgentModel?: string | undefined;
  /**
   * Reset main agent reasoning effort
   */
  mainAgentReasoningEffort?: string | undefined;
  /**
   * Reset preferred provider
   */
  preferredProvider?: string | undefined;
  /**
   * Reset sub agent max tokens
   */
  subAgentMaxTokens?: number | undefined;
  /**
   * Reset sub agent model
   */
  subAgentModel?: string | undefined;
  /**
   * Reset sub agent reasoning effort
   */
  subAgentReasoningEffort?: string | undefined;
  /**
   * Reset timestamp
   */
  updatedAt?: number | undefined;
};

/** @internal */
export const ResetPreferencesResponse$inboundSchema: z.ZodType<
  ResetPreferencesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.number().int().optional(),
  main_agent_max_tokens: z.number().int().optional(),
  main_agent_model: z.string().optional(),
  main_agent_reasoning_effort: z.string().optional(),
  preferred_provider: z.string().optional(),
  sub_agent_max_tokens: z.number().int().optional(),
  sub_agent_model: z.string().optional(),
  sub_agent_reasoning_effort: z.string().optional(),
  updated_at: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "main_agent_max_tokens": "mainAgentMaxTokens",
    "main_agent_model": "mainAgentModel",
    "main_agent_reasoning_effort": "mainAgentReasoningEffort",
    "preferred_provider": "preferredProvider",
    "sub_agent_max_tokens": "subAgentMaxTokens",
    "sub_agent_model": "subAgentModel",
    "sub_agent_reasoning_effort": "subAgentReasoningEffort",
    "updated_at": "updatedAt",
  });
});

export function resetPreferencesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResetPreferencesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResetPreferencesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResetPreferencesResponse' from JSON`,
  );
}
