/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Response type
 */
export const Type = {
  Acknowledge: "acknowledge",
  Text: "text",
  Choice: "choice",
} as const;
/**
 * Response type
 */
export type Type = ClosedEnum<typeof Type>;

export type RespondToNotificationRequestBody = {
  /**
   * Response type
   */
  type: Type;
  /**
   * User's text input or selected choice (optional for acknowledge type)
   */
  value?: string | undefined;
};

export type RespondToNotificationRequest = {
  /**
   * Notification ID
   */
  id: string;
  requestBody: RespondToNotificationRequestBody;
};

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export type RespondToNotificationRequestBody$Outbound = {
  type: string;
  value?: string | undefined;
};

/** @internal */
export const RespondToNotificationRequestBody$outboundSchema: z.ZodType<
  RespondToNotificationRequestBody$Outbound,
  z.ZodTypeDef,
  RespondToNotificationRequestBody
> = z.object({
  type: Type$outboundSchema,
  value: z.string().optional(),
});

export function respondToNotificationRequestBodyToJSON(
  respondToNotificationRequestBody: RespondToNotificationRequestBody,
): string {
  return JSON.stringify(
    RespondToNotificationRequestBody$outboundSchema.parse(
      respondToNotificationRequestBody,
    ),
  );
}

/** @internal */
export type RespondToNotificationRequest$Outbound = {
  id: string;
  RequestBody: RespondToNotificationRequestBody$Outbound;
};

/** @internal */
export const RespondToNotificationRequest$outboundSchema: z.ZodType<
  RespondToNotificationRequest$Outbound,
  z.ZodTypeDef,
  RespondToNotificationRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => RespondToNotificationRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function respondToNotificationRequestToJSON(
  respondToNotificationRequest: RespondToNotificationRequest,
): string {
  return JSON.stringify(
    RespondToNotificationRequest$outboundSchema.parse(
      respondToNotificationRequest,
    ),
  );
}
