/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type SendMessageRequestBody = {
  /**
   * Message content to send
   */
  content: string;
};

export type SendMessageRequest = {
  /**
   * Session ID
   */
  id: string;
  requestBody: SendMessageRequestBody;
};

/**
 * Message sent and processed
 */
export type SendMessageResponse = {
  data?: models.MessageData | undefined;
  error?: models.RESTError | undefined;
  /**
   * Optional message
   */
  message?: string | undefined;
};

/** @internal */
export const SendMessageRequestBody$inboundSchema: z.ZodType<
  SendMessageRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string(),
});

/** @internal */
export type SendMessageRequestBody$Outbound = {
  content: string;
};

/** @internal */
export const SendMessageRequestBody$outboundSchema: z.ZodType<
  SendMessageRequestBody$Outbound,
  z.ZodTypeDef,
  SendMessageRequestBody
> = z.object({
  content: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SendMessageRequestBody$ {
  /** @deprecated use `SendMessageRequestBody$inboundSchema` instead. */
  export const inboundSchema = SendMessageRequestBody$inboundSchema;
  /** @deprecated use `SendMessageRequestBody$outboundSchema` instead. */
  export const outboundSchema = SendMessageRequestBody$outboundSchema;
  /** @deprecated use `SendMessageRequestBody$Outbound` instead. */
  export type Outbound = SendMessageRequestBody$Outbound;
}

export function sendMessageRequestBodyToJSON(
  sendMessageRequestBody: SendMessageRequestBody,
): string {
  return JSON.stringify(
    SendMessageRequestBody$outboundSchema.parse(sendMessageRequestBody),
  );
}

export function sendMessageRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageRequestBody' from JSON`,
  );
}

/** @internal */
export const SendMessageRequest$inboundSchema: z.ZodType<
  SendMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => SendMessageRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type SendMessageRequest$Outbound = {
  id: string;
  RequestBody: SendMessageRequestBody$Outbound;
};

/** @internal */
export const SendMessageRequest$outboundSchema: z.ZodType<
  SendMessageRequest$Outbound,
  z.ZodTypeDef,
  SendMessageRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => SendMessageRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SendMessageRequest$ {
  /** @deprecated use `SendMessageRequest$inboundSchema` instead. */
  export const inboundSchema = SendMessageRequest$inboundSchema;
  /** @deprecated use `SendMessageRequest$outboundSchema` instead. */
  export const outboundSchema = SendMessageRequest$outboundSchema;
  /** @deprecated use `SendMessageRequest$Outbound` instead. */
  export type Outbound = SendMessageRequest$Outbound;
}

export function sendMessageRequestToJSON(
  sendMessageRequest: SendMessageRequest,
): string {
  return JSON.stringify(
    SendMessageRequest$outboundSchema.parse(sendMessageRequest),
  );
}

export function sendMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageRequest' from JSON`,
  );
}

/** @internal */
export const SendMessageResponse$inboundSchema: z.ZodType<
  SendMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.MessageData$inboundSchema.optional(),
  error: models.RESTError$inboundSchema.optional(),
  message: z.string().optional(),
});

/** @internal */
export type SendMessageResponse$Outbound = {
  data?: models.MessageData$Outbound | undefined;
  error?: models.RESTError$Outbound | undefined;
  message?: string | undefined;
};

/** @internal */
export const SendMessageResponse$outboundSchema: z.ZodType<
  SendMessageResponse$Outbound,
  z.ZodTypeDef,
  SendMessageResponse
> = z.object({
  data: models.MessageData$outboundSchema.optional(),
  error: models.RESTError$outboundSchema.optional(),
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SendMessageResponse$ {
  /** @deprecated use `SendMessageResponse$inboundSchema` instead. */
  export const inboundSchema = SendMessageResponse$inboundSchema;
  /** @deprecated use `SendMessageResponse$outboundSchema` instead. */
  export const outboundSchema = SendMessageResponse$outboundSchema;
  /** @deprecated use `SendMessageResponse$Outbound` instead. */
  export type Outbound = SendMessageResponse$Outbound;
}

export function sendMessageResponseToJSON(
  sendMessageResponse: SendMessageResponse,
): string {
  return JSON.stringify(
    SendMessageResponse$outboundSchema.parse(sendMessageResponse),
  );
}

export function sendMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageResponse' from JSON`,
  );
}
