/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Thinking level: off (disabled), basic (4k tokens), medium (10k tokens), maximum (32k tokens). If not provided, determined by keywords in message.
 */
export const ThinkingLevel = {
  Off: "off",
  Basic: "basic",
  Medium: "medium",
  Maximum: "maximum",
} as const;
/**
 * Thinking level: off (disabled), basic (4k tokens), medium (10k tokens), maximum (32k tokens). If not provided, determined by keywords in message.
 */
export type ThinkingLevel = ClosedEnum<typeof ThinkingLevel>;

export type SendMessageRequestBody = {
  /**
   * Maximum tool call iterations for this message. If not provided, unlimited iterations allowed.
   */
  maxSteps?: number | undefined;
  /**
   * Whether the message is in planning mode
   */
  planMode?: boolean | undefined;
  /**
   * The text content of the message
   */
  text: string;
  /**
   * Thinking level: off (disabled), basic (4k tokens), medium (10k tokens), maximum (32k tokens). If not provided, determined by keywords in message.
   */
  thinkingLevel?: ThinkingLevel | null | undefined;
};

export type SendMessageRequest = {
  /**
   * Session ID
   */
  id: string;
  requestBody: SendMessageRequestBody;
};

/**
 * Message accepted for processing. Agent runs asynchronously and streams results via SSE.
 */
export type SendMessageResponse = {
  /**
   * Session ID for the processing task
   */
  sessionId: string;
  /**
   * Processing status
   */
  status: string;
};

/** @internal */
export const ThinkingLevel$outboundSchema: z.ZodNativeEnum<
  typeof ThinkingLevel
> = z.nativeEnum(ThinkingLevel);

/** @internal */
export type SendMessageRequestBody$Outbound = {
  max_steps?: number | undefined;
  plan_mode: boolean;
  text: string;
  thinking_level?: string | null | undefined;
};

/** @internal */
export const SendMessageRequestBody$outboundSchema: z.ZodType<
  SendMessageRequestBody$Outbound,
  z.ZodTypeDef,
  SendMessageRequestBody
> = z.object({
  maxSteps: z.number().int().optional(),
  planMode: z.boolean().default(false),
  text: z.string(),
  thinkingLevel: z.nullable(ThinkingLevel$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    maxSteps: "max_steps",
    planMode: "plan_mode",
    thinkingLevel: "thinking_level",
  });
});

export function sendMessageRequestBodyToJSON(
  sendMessageRequestBody: SendMessageRequestBody,
): string {
  return JSON.stringify(
    SendMessageRequestBody$outboundSchema.parse(sendMessageRequestBody),
  );
}

/** @internal */
export type SendMessageRequest$Outbound = {
  id: string;
  RequestBody: SendMessageRequestBody$Outbound;
};

/** @internal */
export const SendMessageRequest$outboundSchema: z.ZodType<
  SendMessageRequest$Outbound,
  z.ZodTypeDef,
  SendMessageRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => SendMessageRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function sendMessageRequestToJSON(
  sendMessageRequest: SendMessageRequest,
): string {
  return JSON.stringify(
    SendMessageRequest$outboundSchema.parse(sendMessageRequest),
  );
}

/** @internal */
export const SendMessageResponse$inboundSchema: z.ZodType<
  SendMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  sessionId: z.string(),
  status: z.string(),
});

export function sendMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageResponse' from JSON`,
  );
}
