/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Provider name (anthropic, openai, openrouter, gemini, brave)
 */
export const Provider = {
  Anthropic: "anthropic",
  Openai: "openai",
  Openrouter: "openrouter",
  Gemini: "gemini",
  Brave: "brave",
} as const;
/**
 * Provider name (anthropic, openai, openrouter, gemini, brave)
 */
export type Provider = ClosedEnum<typeof Provider>;

export type StoreApiKeyRequest = {
  /**
   * API key for authentication
   */
  apiKey: string;
  /**
   * Provider name (anthropic, openai, openrouter, gemini, brave)
   */
  provider: Provider;
};

/**
 * API key stored status
 */
export type StoreApiKeyResponse = {
  /**
   * Success message
   */
  message?: string | undefined;
  /**
   * Provider name
   */
  provider?: string | undefined;
  /**
   * Operation status (success)
   */
  status?: string | undefined;
};

/** @internal */
export const Provider$outboundSchema: z.ZodNativeEnum<typeof Provider> = z
  .nativeEnum(Provider);

/** @internal */
export type StoreApiKeyRequest$Outbound = {
  api_key: string;
  provider: string;
};

/** @internal */
export const StoreApiKeyRequest$outboundSchema: z.ZodType<
  StoreApiKeyRequest$Outbound,
  z.ZodTypeDef,
  StoreApiKeyRequest
> = z.object({
  apiKey: z.string(),
  provider: Provider$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    apiKey: "api_key",
  });
});

export function storeApiKeyRequestToJSON(
  storeApiKeyRequest: StoreApiKeyRequest,
): string {
  return JSON.stringify(
    StoreApiKeyRequest$outboundSchema.parse(storeApiKeyRequest),
  );
}

/** @internal */
export const StoreApiKeyResponse$inboundSchema: z.ZodType<
  StoreApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  provider: z.string().optional(),
  status: z.string().optional(),
});

export function storeApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<StoreApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StoreApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StoreApiKeyResponse' from JSON`,
  );
}
