/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateSessionCallbacksRequestBody = {
  /**
   * Session-level callbacks that execute after tool completion. Environment variables available: CALLBACK_TOOL_RESULT, CALLBACK_TOOL_NAME, CALLBACK_TOOL_ID, CALLBACK_SESSION_ID
   */
  callbacks: Array<models.Callback>;
};

export type UpdateSessionCallbacksRequest = {
  /**
   * Session ID to update
   */
  id: string;
  requestBody: UpdateSessionCallbacksRequestBody;
};

/** @internal */
export type UpdateSessionCallbacksRequestBody$Outbound = {
  callbacks: Array<models.Callback$Outbound>;
};

/** @internal */
export const UpdateSessionCallbacksRequestBody$outboundSchema: z.ZodType<
  UpdateSessionCallbacksRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateSessionCallbacksRequestBody
> = z.object({
  callbacks: z.array(models.Callback$outboundSchema),
});

export function updateSessionCallbacksRequestBodyToJSON(
  updateSessionCallbacksRequestBody: UpdateSessionCallbacksRequestBody,
): string {
  return JSON.stringify(
    UpdateSessionCallbacksRequestBody$outboundSchema.parse(
      updateSessionCallbacksRequestBody,
    ),
  );
}

/** @internal */
export type UpdateSessionCallbacksRequest$Outbound = {
  id: string;
  RequestBody: UpdateSessionCallbacksRequestBody$Outbound;
};

/** @internal */
export const UpdateSessionCallbacksRequest$outboundSchema: z.ZodType<
  UpdateSessionCallbacksRequest$Outbound,
  z.ZodTypeDef,
  UpdateSessionCallbacksRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateSessionCallbacksRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateSessionCallbacksRequestToJSON(
  updateSessionCallbacksRequest: UpdateSessionCallbacksRequest,
): string {
  return JSON.stringify(
    UpdateSessionCallbacksRequest$outboundSchema.parse(
      updateSessionCallbacksRequest,
    ),
  );
}
