/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type UploadSessionFileRequestBody = {
  /**
   * File to upload
   */
  file: FileT | Blob;
};

export type UploadSessionFileRequest = {
  /**
   * Session ID
   */
  id: string;
  requestBody: UploadSessionFileRequestBody;
};

/** @internal */
export const FileT$inboundSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileT$ {
  /** @deprecated use `FileT$inboundSchema` instead. */
  export const inboundSchema = FileT$inboundSchema;
  /** @deprecated use `FileT$outboundSchema` instead. */
  export const outboundSchema = FileT$outboundSchema;
  /** @deprecated use `FileT$Outbound` instead. */
  export type Outbound = FileT$Outbound;
}

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

export function fileFromJSON(
  jsonString: string,
): SafeParseResult<FileT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileT' from JSON`,
  );
}

/** @internal */
export const UploadSessionFileRequestBody$inboundSchema: z.ZodType<
  UploadSessionFileRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  file: z.lazy(() => FileT$inboundSchema),
});

/** @internal */
export type UploadSessionFileRequestBody$Outbound = {
  file: FileT$Outbound | Blob;
};

/** @internal */
export const UploadSessionFileRequestBody$outboundSchema: z.ZodType<
  UploadSessionFileRequestBody$Outbound,
  z.ZodTypeDef,
  UploadSessionFileRequestBody
> = z.object({
  file: z.lazy(() => FileT$outboundSchema).or(blobLikeSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UploadSessionFileRequestBody$ {
  /** @deprecated use `UploadSessionFileRequestBody$inboundSchema` instead. */
  export const inboundSchema = UploadSessionFileRequestBody$inboundSchema;
  /** @deprecated use `UploadSessionFileRequestBody$outboundSchema` instead. */
  export const outboundSchema = UploadSessionFileRequestBody$outboundSchema;
  /** @deprecated use `UploadSessionFileRequestBody$Outbound` instead. */
  export type Outbound = UploadSessionFileRequestBody$Outbound;
}

export function uploadSessionFileRequestBodyToJSON(
  uploadSessionFileRequestBody: UploadSessionFileRequestBody,
): string {
  return JSON.stringify(
    UploadSessionFileRequestBody$outboundSchema.parse(
      uploadSessionFileRequestBody,
    ),
  );
}

export function uploadSessionFileRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionFileRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionFileRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionFileRequestBody' from JSON`,
  );
}

/** @internal */
export const UploadSessionFileRequest$inboundSchema: z.ZodType<
  UploadSessionFileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => UploadSessionFileRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UploadSessionFileRequest$Outbound = {
  id: string;
  RequestBody: UploadSessionFileRequestBody$Outbound;
};

/** @internal */
export const UploadSessionFileRequest$outboundSchema: z.ZodType<
  UploadSessionFileRequest$Outbound,
  z.ZodTypeDef,
  UploadSessionFileRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UploadSessionFileRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UploadSessionFileRequest$ {
  /** @deprecated use `UploadSessionFileRequest$inboundSchema` instead. */
  export const inboundSchema = UploadSessionFileRequest$inboundSchema;
  /** @deprecated use `UploadSessionFileRequest$outboundSchema` instead. */
  export const outboundSchema = UploadSessionFileRequest$outboundSchema;
  /** @deprecated use `UploadSessionFileRequest$Outbound` instead. */
  export type Outbound = UploadSessionFileRequest$Outbound;
}

export function uploadSessionFileRequestToJSON(
  uploadSessionFileRequest: UploadSessionFileRequest,
): string {
  return JSON.stringify(
    UploadSessionFileRequest$outboundSchema.parse(uploadSessionFileRequest),
  );
}

export function uploadSessionFileRequestFromJSON(
  jsonString: string,
): SafeParseResult<UploadSessionFileRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadSessionFileRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadSessionFileRequest' from JSON`,
  );
}
