/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CallbackResultData,
  CallbackResultData$inboundSchema,
} from "./callbackresultdata.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { ToolCallData, ToolCallData$inboundSchema } from "./toolcalldata.js";

/**
 * Backend message structure representing a complete message exchange
 */
export type BackendMessage = {
  /**
   * Assistant's response message (optional)
   */
  assistantResponse?: string | undefined;
  /**
   * Tokens used for prompt cache creation (optional)
   */
  cacheCreationTokens?: number | undefined;
  /**
   * Tokens read from prompt cache (optional)
   */
  cacheReadTokens?: number | undefined;
  /**
   * Callback execution results (optional)
   */
  callbackResults?: Array<CallbackResultData> | undefined;
  /**
   * Cost for this specific message in USD
   */
  cost?: number | undefined;
  /**
   * Unique message identifier
   */
  id: string;
  /**
   * Input tokens used for this message (includes cache creation)
   */
  inputTokens?: number | undefined;
  /**
   * Model used for this message (e.g., 'claude-sonnet-4')
   */
  model?: string | undefined;
  /**
   * Output tokens generated for this message (includes cache reads)
   */
  outputTokens?: number | undefined;
  /**
   * Reasoning process (optional)
   */
  reasoning?: string | undefined;
  /**
   * Reasoning duration in milliseconds (optional)
   */
  reasoningDuration?: number | undefined;
  /**
   * Message role (user, assistant, tool)
   */
  role: string;
  /**
   * Session identifier
   */
  sessionId: string;
  /**
   * Tool calls made during message processing
   */
  toolCalls?: Array<ToolCallData> | undefined;
  /**
   * User's input message
   */
  userInput: string;
};

/** @internal */
export const BackendMessage$inboundSchema: z.ZodType<
  BackendMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  assistantResponse: z.string().optional(),
  cacheCreationTokens: z.number().int().optional(),
  cacheReadTokens: z.number().int().optional(),
  callbackResults: z.array(CallbackResultData$inboundSchema).optional(),
  cost: z.number().optional(),
  id: z.string(),
  inputTokens: z.number().int().optional(),
  model: z.string().optional(),
  outputTokens: z.number().int().optional(),
  reasoning: z.string().optional(),
  reasoningDuration: z.number().int().optional(),
  role: z.string(),
  sessionId: z.string(),
  toolCalls: z.array(ToolCallData$inboundSchema).optional(),
  userInput: z.string(),
});

export function backendMessageFromJSON(
  jsonString: string,
): SafeParseResult<BackendMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BackendMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BackendMessage' from JSON`,
  );
}
