/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Core built-in tool names
 */
export const CoreToolName = {
  Bash: "bash",
  ReadText: "ReadText",
  Glob: "glob",
  ReadMedia: "ReadMedia",
  Grep: "grep",
  Write: "write",
  Edit: "edit",
  PythonExecution: "python_execution",
  Search: "search",
  TodoWrite: "todo_write",
  ExitPlanMode: "exit_plan_mode",
  ShowMedia: "show_media",
  Task: "task",
} as const;
/**
 * Core built-in tool names
 */
export type CoreToolName = ClosedEnum<typeof CoreToolName>;

/** @internal */
export const CoreToolName$inboundSchema: z.ZodNativeEnum<typeof CoreToolName> =
  z.nativeEnum(CoreToolName);

/** @internal */
export const CoreToolName$outboundSchema: z.ZodNativeEnum<typeof CoreToolName> =
  CoreToolName$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CoreToolName$ {
  /** @deprecated use `CoreToolName$inboundSchema` instead. */
  export const inboundSchema = CoreToolName$inboundSchema;
  /** @deprecated use `CoreToolName$outboundSchema` instead. */
  export const outboundSchema = CoreToolName$outboundSchema;
}
