/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Core built-in tool names
 */
export const CoreToolName = {
  Bash: "Bash",
  ReadText: "ReadText",
  Glob: "Glob",
  ReadMedia: "ReadMedia",
  Grep: "Grep",
  Write: "Write",
  Edit: "Edit",
  PythonExecution: "python_execution",
  Search: "Search",
  TodoWrite: "TodoWrite",
  ExitPlanMode: "ExitPlanMode",
  ShowMedia: "ShowMedia",
  Task: "Task",
} as const;
/**
 * Core built-in tool names
 */
export type CoreToolName = ClosedEnum<typeof CoreToolName>;

/** @internal */
export const CoreToolName$inboundSchema: z.ZodNativeEnum<typeof CoreToolName> =
  z.nativeEnum(CoreToolName);

/** @internal */
export const CoreToolName$outboundSchema: z.ZodNativeEnum<typeof CoreToolName> =
  CoreToolName$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CoreToolName$ {
  /** @deprecated use `CoreToolName$inboundSchema` instead. */
  export const inboundSchema = CoreToolName$inboundSchema;
  /** @deprecated use `CoreToolName$outboundSchema` instead. */
  export const outboundSchema = CoreToolName$outboundSchema;
}
