/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Core built-in tool names
 */
export const CoreToolName = {
  Bash: "Bash",
  ReadText: "ReadText",
  Glob: "Glob",
  ReadMedia: "ReadMedia",
  Grep: "Grep",
  Write: "Write",
  Edit: "Edit",
  PythonExecution: "python_execution",
  Search: "Search",
  TodoWrite: "TodoWrite",
  ExitPlanMode: "ExitPlanMode",
  Show: "Show",
  Task: "Task",
} as const;
/**
 * Core built-in tool names
 */
export type CoreToolName = ClosedEnum<typeof CoreToolName>;

/** @internal */
export const CoreToolName$inboundSchema: z.ZodNativeEnum<typeof CoreToolName> =
  z.nativeEnum(CoreToolName);
