/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FileInfo = {
  /**
   * Whether this is a directory
   */
  isDir: boolean;
  /**
   * Last modified timestamp (Unix time)
   */
  modified: number;
  /**
   * File name
   */
  name: string;
  /**
   * File size in bytes
   */
  size: number;
  /**
   * Static URL to access the file
   */
  url: string;
};

/** @internal */
export const FileInfo$inboundSchema: z.ZodType<
  FileInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  isDir: z.boolean(),
  modified: z.number().int(),
  name: z.string(),
  size: z.number().int(),
  url: z.string(),
});

export function fileInfoFromJSON(
  jsonString: string,
): SafeParseResult<FileInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileInfo' from JSON`,
  );
}
