/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Message role
 */
export const MessageRole = {
  User: "user",
  Assistant: "assistant",
} as const;
/**
 * Message role
 */
export type MessageRole = ClosedEnum<typeof MessageRole>;

/** @internal */
export const MessageRole$inboundSchema: z.ZodNativeEnum<typeof MessageRole> = z
  .nativeEnum(MessageRole);

/** @internal */
export const MessageRole$outboundSchema: z.ZodNativeEnum<typeof MessageRole> =
  MessageRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessageRole$ {
  /** @deprecated use `MessageRole$inboundSchema` instead. */
  export const inboundSchema = MessageRole$inboundSchema;
  /** @deprecated use `MessageRole$outboundSchema` instead. */
  export const outboundSchema = MessageRole$outboundSchema;
}
