/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Callback type
 */
export const SessionDataType = {
  BashScript: "bash_script",
  SubAgent: "sub_agent",
} as const;
/**
 * Callback type
 */
export type SessionDataType = ClosedEnum<typeof SessionDataType>;

export type Callback = {
  /**
   * Bash command to execute (for bash_script type)
   */
  bashCommand?: string | undefined;
  /**
   * Timeout in milliseconds for bash execution
   */
  bashTimeout?: number | undefined;
  /**
   * Run callback asynchronously
   */
  nonBlocking?: boolean | undefined;
  /**
   * Tool to attach callback to
   */
  toolName?: string | undefined;
  /**
   * Callback type
   */
  type?: SessionDataType | undefined;
};

/**
 * Session type:
 *
 * @remarks
 * - 'main': Root-level user interactions
 * - 'forked': User-created conversation branches
 * - 'subagent': Delegated task workers
 */
export const SessionType = {
  Main: "main",
  Forked: "forked",
  Subagent: "subagent",
} as const;
/**
 * Session type:
 *
 * @remarks
 * - 'main': Root-level user interactions
 * - 'forked': User-created conversation branches
 * - 'subagent': Delegated task workers
 */
export type SessionType = ClosedEnum<typeof SessionType>;

/**
 * Subagent specialization type (only present for subagent sessions)
 */
export const SubagentType = {
  GeneralPurpose: "general-purpose",
} as const;
/**
 * Subagent specialization type (only present for subagent sessions)
 */
export type SubagentType = ClosedEnum<typeof SubagentType>;

export type SessionData = {
  /**
   * Number of assistant messages in session
   */
  assistantMessageCount: number;
  /**
   * Session-level callback configurations (optional)
   */
  callbacks?: Array<Callback> | undefined;
  /**
   * Total completion tokens used
   */
  completionTokens: number;
  /**
   * Total cost of session (for subagent sessions, costs are also accumulated in parent session)
   */
  cost: number;
  /**
   * Session creation timestamp
   */
  createdAt: Date;
  /**
   * First user message (optional)
   */
  firstUserMessage?: string | undefined;
  /**
   * Unique session identifier
   */
  id: string;
  /**
   * Parent session ID for forked and subagent sessions (null for main sessions)
   */
  parentSessionId?: string | undefined;
  /**
   * ID of the tool call that spawned this subagent session (null for non-subagent sessions)
   */
  parentToolCallId?: string | undefined;
  /**
   * Total prompt tokens used
   */
  promptTokens: number;
  /**
   * Session type:
   *
   * @remarks
   * - 'main': Root-level user interactions
   * - 'forked': User-created conversation branches
   * - 'subagent': Delegated task workers
   */
  sessionType: SessionType;
  /**
   * Subagent specialization type (only present for subagent sessions)
   */
  subagentType?: SubagentType | undefined;
  /**
   * Session title
   */
  title: string;
  /**
   * Number of tool calls made in session
   */
  toolCallCount: number;
  /**
   * Number of user messages in session
   */
  userMessageCount: number;
};

/** @internal */
export const SessionDataType$inboundSchema: z.ZodNativeEnum<
  typeof SessionDataType
> = z.nativeEnum(SessionDataType);

/** @internal */
export const SessionDataType$outboundSchema: z.ZodNativeEnum<
  typeof SessionDataType
> = SessionDataType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SessionDataType$ {
  /** @deprecated use `SessionDataType$inboundSchema` instead. */
  export const inboundSchema = SessionDataType$inboundSchema;
  /** @deprecated use `SessionDataType$outboundSchema` instead. */
  export const outboundSchema = SessionDataType$outboundSchema;
}

/** @internal */
export const Callback$inboundSchema: z.ZodType<
  Callback,
  z.ZodTypeDef,
  unknown
> = z.object({
  bashCommand: z.string().optional(),
  bashTimeout: z.number().int().optional(),
  nonBlocking: z.boolean().optional(),
  toolName: z.string().optional(),
  type: SessionDataType$inboundSchema.optional(),
});

/** @internal */
export type Callback$Outbound = {
  bashCommand?: string | undefined;
  bashTimeout?: number | undefined;
  nonBlocking?: boolean | undefined;
  toolName?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const Callback$outboundSchema: z.ZodType<
  Callback$Outbound,
  z.ZodTypeDef,
  Callback
> = z.object({
  bashCommand: z.string().optional(),
  bashTimeout: z.number().int().optional(),
  nonBlocking: z.boolean().optional(),
  toolName: z.string().optional(),
  type: SessionDataType$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Callback$ {
  /** @deprecated use `Callback$inboundSchema` instead. */
  export const inboundSchema = Callback$inboundSchema;
  /** @deprecated use `Callback$outboundSchema` instead. */
  export const outboundSchema = Callback$outboundSchema;
  /** @deprecated use `Callback$Outbound` instead. */
  export type Outbound = Callback$Outbound;
}

export function callbackToJSON(callback: Callback): string {
  return JSON.stringify(Callback$outboundSchema.parse(callback));
}

export function callbackFromJSON(
  jsonString: string,
): SafeParseResult<Callback, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Callback$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Callback' from JSON`,
  );
}

/** @internal */
export const SessionType$inboundSchema: z.ZodNativeEnum<typeof SessionType> = z
  .nativeEnum(SessionType);

/** @internal */
export const SessionType$outboundSchema: z.ZodNativeEnum<typeof SessionType> =
  SessionType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SessionType$ {
  /** @deprecated use `SessionType$inboundSchema` instead. */
  export const inboundSchema = SessionType$inboundSchema;
  /** @deprecated use `SessionType$outboundSchema` instead. */
  export const outboundSchema = SessionType$outboundSchema;
}

/** @internal */
export const SubagentType$inboundSchema: z.ZodNativeEnum<typeof SubagentType> =
  z.nativeEnum(SubagentType);

/** @internal */
export const SubagentType$outboundSchema: z.ZodNativeEnum<typeof SubagentType> =
  SubagentType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubagentType$ {
  /** @deprecated use `SubagentType$inboundSchema` instead. */
  export const inboundSchema = SubagentType$inboundSchema;
  /** @deprecated use `SubagentType$outboundSchema` instead. */
  export const outboundSchema = SubagentType$outboundSchema;
}

/** @internal */
export const SessionData$inboundSchema: z.ZodType<
  SessionData,
  z.ZodTypeDef,
  unknown
> = z.object({
  assistantMessageCount: z.number().int(),
  callbacks: z.array(z.lazy(() => Callback$inboundSchema)).optional(),
  completionTokens: z.number().int(),
  cost: z.number(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  firstUserMessage: z.string().optional(),
  id: z.string(),
  parentSessionId: z.string().optional(),
  parentToolCallId: z.string().optional(),
  promptTokens: z.number().int(),
  sessionType: SessionType$inboundSchema,
  subagentType: SubagentType$inboundSchema.optional(),
  title: z.string(),
  toolCallCount: z.number().int(),
  userMessageCount: z.number().int(),
});

/** @internal */
export type SessionData$Outbound = {
  assistantMessageCount: number;
  callbacks?: Array<Callback$Outbound> | undefined;
  completionTokens: number;
  cost: number;
  createdAt: string;
  firstUserMessage?: string | undefined;
  id: string;
  parentSessionId?: string | undefined;
  parentToolCallId?: string | undefined;
  promptTokens: number;
  sessionType: string;
  subagentType?: string | undefined;
  title: string;
  toolCallCount: number;
  userMessageCount: number;
};

/** @internal */
export const SessionData$outboundSchema: z.ZodType<
  SessionData$Outbound,
  z.ZodTypeDef,
  SessionData
> = z.object({
  assistantMessageCount: z.number().int(),
  callbacks: z.array(z.lazy(() => Callback$outboundSchema)).optional(),
  completionTokens: z.number().int(),
  cost: z.number(),
  createdAt: z.date().transform(v => v.toISOString()),
  firstUserMessage: z.string().optional(),
  id: z.string(),
  parentSessionId: z.string().optional(),
  parentToolCallId: z.string().optional(),
  promptTokens: z.number().int(),
  sessionType: SessionType$outboundSchema,
  subagentType: SubagentType$outboundSchema.optional(),
  title: z.string(),
  toolCallCount: z.number().int(),
  userMessageCount: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SessionData$ {
  /** @deprecated use `SessionData$inboundSchema` instead. */
  export const inboundSchema = SessionData$inboundSchema;
  /** @deprecated use `SessionData$outboundSchema` instead. */
  export const outboundSchema = SessionData$outboundSchema;
  /** @deprecated use `SessionData$Outbound` instead. */
  export type Outbound = SessionData$Outbound;
}

export function sessionDataToJSON(sessionData: SessionData): string {
  return JSON.stringify(SessionData$outboundSchema.parse(sessionData));
}

export function sessionDataFromJSON(
  jsonString: string,
): SafeParseResult<SessionData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SessionData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SessionData' from JSON`,
  );
}
