/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Callback, Callback$inboundSchema } from "./callback.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Session type:
 *
 * @remarks
 * - 'main': Root-level user interactions
 * - 'subagent': Delegated task workers
 */
export const SessionType = {
  Main: "main",
  Subagent: "subagent",
} as const;
/**
 * Session type:
 *
 * @remarks
 * - 'main': Root-level user interactions
 * - 'subagent': Delegated task workers
 */
export type SessionType = ClosedEnum<typeof SessionType>;

/**
 * Subagent specialization type (only present for subagent sessions)
 */
export const SubagentType = {
  GeneralPurpose: "general-purpose",
} as const;
/**
 * Subagent specialization type (only present for subagent sessions)
 */
export type SubagentType = ClosedEnum<typeof SubagentType>;

export type SessionData = {
  /**
   * Number of assistant messages in session
   */
  assistantMessageCount: number;
  /**
   * Session-level callback configurations (optional)
   */
  callbacks?: Array<Callback> | undefined;
  /**
   * Total completion tokens used
   */
  completionTokens: number;
  /**
   * Total cost of session (for subagent sessions, costs are also accumulated in parent session)
   */
  cost: number;
  /**
   * Session creation timestamp
   */
  createdAt: Date;
  /**
   * First user message (optional)
   */
  firstUserMessage?: string | undefined;
  /**
   * Unique session identifier
   */
  id: string;
  /**
   * Parent session ID for subagent sessions (null for main sessions)
   */
  parentSessionId?: string | undefined;
  /**
   * ID of the tool call that spawned this subagent session (null for non-subagent sessions)
   */
  parentToolCallId?: string | undefined;
  /**
   * Total prompt tokens used
   */
  promptTokens: number;
  /**
   * Session type:
   *
   * @remarks
   * - 'main': Root-level user interactions
   * - 'subagent': Delegated task workers
   */
  sessionType: SessionType;
  /**
   * Subagent specialization type (only present for subagent sessions)
   */
  subagentType?: SubagentType | undefined;
  /**
   * Session title
   */
  title: string;
  /**
   * Number of tool calls made in session
   */
  toolCallCount: number;
  /**
   * Number of user messages in session
   */
  userMessageCount: number;
};

/** @internal */
export const SessionType$inboundSchema: z.ZodNativeEnum<typeof SessionType> = z
  .nativeEnum(SessionType);

/** @internal */
export const SubagentType$inboundSchema: z.ZodNativeEnum<typeof SubagentType> =
  z.nativeEnum(SubagentType);

/** @internal */
export const SessionData$inboundSchema: z.ZodType<
  SessionData,
  z.ZodTypeDef,
  unknown
> = z.object({
  assistantMessageCount: z.number().int(),
  callbacks: z.array(Callback$inboundSchema).optional(),
  completionTokens: z.number().int(),
  cost: z.number(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  firstUserMessage: z.string().optional(),
  id: z.string(),
  parentSessionId: z.string().optional(),
  parentToolCallId: z.string().optional(),
  promptTokens: z.number().int(),
  sessionType: SessionType$inboundSchema,
  subagentType: SubagentType$inboundSchema.optional(),
  title: z.string(),
  toolCallCount: z.number().int(),
  userMessageCount: z.number().int(),
});

export function sessionDataFromJSON(
  jsonString: string,
): SafeParseResult<SessionData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SessionData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SessionData' from JSON`,
  );
}
