/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { ToolName, ToolName$inboundSchema } from "./toolname.js";

export type ToolCallData = {
  /**
   * Whether tool call has finished
   */
  finished: boolean;
  /**
   * Unique tool call identifier
   */
  id: string;
  /**
   * Tool input parameters
   */
  input: string;
  /**
   * Whether tool call resulted in error (optional)
   */
  isError?: boolean | undefined;
  /**
   * Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern
   */
  name: ToolName;
  /**
   * Tool execution result (optional)
   */
  result?: string | undefined;
  /**
   * Screenshot URLs captured during tool execution (optional)
   */
  screenshotUrls?: Array<string> | undefined;
  /**
   * Tool type
   */
  type: string;
};

/** @internal */
export const ToolCallData$inboundSchema: z.ZodType<
  ToolCallData,
  z.ZodTypeDef,
  unknown
> = z.object({
  finished: z.boolean(),
  id: z.string(),
  input: z.string(),
  isError: z.boolean().optional(),
  name: ToolName$inboundSchema,
  result: z.string().optional(),
  screenshotUrls: z.array(z.string()).optional(),
  type: z.string(),
});

export function toolCallDataFromJSON(
  jsonString: string,
): SafeParseResult<ToolCallData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolCallData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolCallData' from JSON`,
  );
}
